---
title: "data transformation"
author: "Max"
date: "2024-03-06"
output: html_document
---

```{r}
clusters = cluster_labels
clusters$cities = rownames(clusters)
cities_w_clusters = cities_clean %>% left_join(clusters, by = join_by("geo_label_city" == "cities"))
```

```{r}
# Assuming the data is tab-separated
happy <- read_csv("data/happiest_places_to_live.csv")
happy <- happy %>% filter(!is.na(City))
head(happy)
## Edit names to make them equal
happy <- happy %>%
  mutate(City = ifelse(City == "Detroit, MI", "Detroit", City)) %>% 
  mutate(City = ifelse(City == "Washington, DC", "Washington", City)) %>% 
  mutate(City = ifelse(City == "New York", "New York City", City))
```

```{r}
## Join 
final = cities_w_clusters %>% left_join(happy, by = join_by(geo_label_city == City))
response_cols = final %>% select(any_of(colnames(happy)))
colnames(response_cols)
```
## Compare rankings to clusters

```{r}
rankings = final %>% select(ends_with("Rank"), ends_with("Score"), geo_label_city, Cluster)
```


```{r}
df_averages <- rankings %>%
  group_by(Cluster) %>%
  summarise(
    avg_Rank = mean(`Overall Rank`, na.rm = TRUE),
    avg_wellbeing = mean(`Emotional and Physical Well-being Rank`, na.rm = TRUE),
    avg_finance = mean(`Income and Employment Rank`, na.rm = TRUE),
    avg_env= mean(`Community and Environment Rank`, na.rm = TRUE),
    avg_Score = mean(`Total Score`, na.rm = TRUE)
  )

# View the results
print(df_averages)
#correlate(df_averages %>% select(!Cluster))
```
```{r}
df_long <- rankings %>%
  pivot_longer(cols = ends_with("Rank"), names_to = "ranking", values_to = "value")
```

```{r}
ggplot(df_long, aes(x = Cluster, y = value, fill = ranking)) +
  geom_boxplot() +
  theme_bw() +
  labs(title = "Ranking Distribution by Cluster", x = "Cluster", y = "Ranking")
```

```{r}
ggplot(df_long, aes(x = Cluster, y = value, fill = ranking)) +
  geom_violin() +
  theme_bw() +
  labs(title = "Ranking Distribution by Cluster", x = "Cluster", y = "Ranking")
```

```{r}
df_summary <- df_long %>%
  group_by(Cluster, ranking) %>%
  summarize(mean_value = mean(value, na.rm = TRUE))

ggplot(df_summary, aes(x = Cluster, y = mean_value, fill = ranking)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  labs(title = "Average Ranking by Cluster", x = "Cluster", y = "Average Ranking")
```

```{r}
ggplot(df_long, aes(x = Cluster, y = value, color = ranking)) +
  geom_point(position = position_jitterdodge()) +
  theme_bw() +
  labs(title = "Rankings by Cluster", x = "Cluster", y = "Ranking")
```
https://www.census.gov/data/tables/time-series/demo/popest/2020s-total-metro-and-micro-statistical-areas.html


```{r}
pop_change = read.csv("pop_change.csv")
```

```{r}
## Mutate: pull first -,
## 
```

